modLoader="javafml"
loaderVersion="[34,)"
issueTrackerURL="https://github.com/pau101/JEI-Professions/issues"
license="MIT"
[[mods]]
    modId="jeiprofessions"
    version="${version}"
    displayName="JEI Professions"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/jei-professions"
    authors="pau101"
    description="A JEI plugin for viewing villager profession job sites"
[[dependencies.jeiprofessions]]
    modId="forge"
    mandatory=true
    versionRange="[34,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.jeiprofessions]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16,1.17)"
    ordering="NONE"
    side="BOTH"
[[dependencies.jeiprofessions]]
    modId="jei"
    mandatory=true
    versionRange="[7,)"
    ordering="AFTER"
    side="BOTH"
